---
title: "Contig Bin Plot"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---
```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)

library(tidyverse)

# define negate
'%ni%' <- Negate('%in%')

combo_df <- read.csv(file = "combo_df.csv")


combo_df$Contig[combo_df$Contig %ni% coverage_df$Contig]

# 3078 contigs with no bins
table(is.na(combo_df$bin))

```




```{r import data}

# read in the coverage df
coverage_df <- read.csv(file = 'corrected_coverage.tsv', sep = '\t')
colnames(coverage_df) <- gsub( "X", "", colnames(coverage_df))


combined_coverage_meta_df <- merge(combo_df %>% dplyr::select(Contig,bin,bin_length,length), coverage_df)

# filter only contigs with bins 

combined_coverage_meta_df <- combined_coverage_meta_df %>% 
  filter(!is.na(bin))

# split dataframes by bin 

bin_split_df_list <-split(combined_coverage_meta_df, combined_coverage_meta_df$bin)

bins <- c()
# 61 samples
# 75 bins
num_samples <- 61
bin_count <- length(unique(combined_coverage_meta_df$bin))

bin_cov_means_df <- data.frame(matrix(NA, nrow = bin_count, ncol = num_samples))


for (i in 1:bin_count){
  
  df <- bin_split_df[[i]]
  
  bin <- bin_split_df[[i]]$bin[1]
  
  # length = contig length
  # bin_length = bin length
  df[,-c(1:4)] <-  df[,-c(1:4)] * df$length / df$bin_length
  
  bin_cov_mean <- colMeans(df[,-c(1:4)] )
  
  bins <- append(bins, bin)
  bin_cov_means_df[i,] <-  bin_cov_mean
  
}

# rename cols with samples
colnames(bin_cov_means_df) <-  colnames(bin_split_df[[1]][,-c(1:4)])

bin_cov_means_df$bin <- bins
bin_cov_means_df <- bin_cov_means_df %>%  
  relocate(bin)


meta_df <- unique(combo_df %>%  dplyr::select(bin, bin_length, classification, Species))

# this is the df with the bin level normalised coverages

bin_cov_means_combo_df <- merge(meta_df,bin_cov_means_df )

#### bin means

bin_row_means <- rowMeans(bin_cov_means_df[,-1])
bin_row_means_df <- data.frame(bin = bin_cov_means_df$bin,
                            mean = bin_row_means)

bin_row_means_df <- merge(bin_row_means_df, meta_df)



# bin_row_means_df <- bin_row_means_df %>% 
#   arrange(desc(mean))

# top_10_bins <- bin_row_means_df$bin[1:10]

```

```{r get extra data}

checkm_data <- read.csv(file = "cross_assembly_checkm_parsed.csv")
checkm_data <- checkm_data %>% dplyr::select(bin, Completeness, Contamination, Strain_heterogeneity)

bin_row_means_df <- merge(bin_row_means_df, checkm_data)


```

```{r staph bin}

staph_coverage <- bin_cov_means_df %>% 
  filter(bin == "bin_47") 


names(staph_coverage)[staph_coverage > 2]



```

```{r heatmap}


# bin_cov_means_df <- bin_cov_means_df 
# %>% 
#   filter(bin %ni% top_10_bins)

coverage_mat <- as.matrix(bin_cov_means_df[,-1])

coverage_mat <- log2(coverage_mat+0.5)

row.names(coverage_mat) <- bin_cov_means_df$bin

library(pheatmap)

spec.anno_row <- data.frame(bin_means = bin_row_means_df$mean, 
                            bin_lengths = bin_row_means_df$bin_length,
                            Completeness = bin_row_means_df$Completeness,
                            Contamination = bin_row_means_df$Contamination,
                             Strain_heterogeneity = bin_row_means_df$Strain_heterogeneity)

rownames(spec.anno_row) <- rownames(coverage_mat)

# get the Patient and Dates
spl <- strsplit(as.character(colnames(coverage_df)), "_")

Patient <- sapply(spl, "[", 1)
Patient <- Patient[-1]

patients_with_multiple_samples <- names(table(Patient)[table(Patient) > 1])
total_samples_multi_patient <- sum(table(Patient)[table(Patient) > 1])

# spec.anno_colors <- list(bin_means = colorRampPalette(c("blue", "white", "red"))(10),bin_lengths =  colorRampPalette(c("blue", "white", "red"))(10))

spec.anno_col <- data.frame(Patient = as.character(Patient))
row.names(spec.anno_col) <- colnames(coverage_mat)


jpeg(file = paste0("Plots/", "bin_coverage_heatmap.jpeg"), units = "in", 
     width = 8, 
     height = 6,  
     bg = "transparent", 
     res = 600) 
pheatmap(coverage_mat, 
         cluster_rows = TRUE, 
         cluster_cols = TRUE, 
         show_colnames = FALSE,
         show_rownames = TRUE,
         fontsize_row = 5.5, 
         fontsize_col = 5.5,
         fontsize = 12,
         clustering_distance_rows = 'euclidean',
         clustering_method = 'ward.D',
         treeheight_row = 30,
         annotation_row = spec.anno_row,
         annotation_col = spec.anno_col,
         #annotation_colors = spec.anno_colors,
         border_color = 'NA')
dev.off()

```


```{r multiple samples}

# all cols with patients in multiple samples
Patient %in% patients_with_multiple_samples

spec.anno_col_multi_patients <- spec.anno_col %>% filter(Patient %in% patients_with_multiple_samples)

jpeg(file = paste0("Plots/", "bin_coverage_heatmap_patients_with_multiple_samples.jpeg"), units = "in", 
     width = 8, 
     height = 6,  
     bg = "transparent", 
     res = 600) 

pheatmap(coverage_mat[,Patient %in% patients_with_multiple_samples], 
         cluster_rows = TRUE, 
         cluster_cols = TRUE, 
         show_colnames = FALSE,
         show_rownames = TRUE,
         fontsize_row = 5, 
         fontsize_col = 5,
         fontsize = 12,
         clustering_distance_rows = 'euclidean',
         clustering_method = 'ward.D',
         treeheight_row = 30,
         annotation_row = spec.anno_row,
         annotation_col = spec.anno_col_multi_patients,
         #annotation_colors = spec.anno_colors,
         border_color = 'NA')
dev.off()
```
